version: 0.0
os: linux
files:
  - source: src/index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: ./scripts/before_install
      timeout: 3000
      runas: ubuntu
  AfterInstall:
    - location: scripts/restart_server
      timeout: 3000
      runas: ubuntu
