version: 0.0
os: linux
files:
  - source: /src/
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/restart_server
      timeout: 300
      runas: ubuntu
